Algoritmo "ExemploOperadores"

Var
Nome: CARACTERE;
idade: REAL;
Inicio
escreva("Digite o nome:")
leia(nome)
escreval(nome+"Monteiro")
escreval("Digite a idade")
leia(idade)
escreval("Idade:",idade)
escreval("Idade maior que 18:",(idade>18))
escreval("Idade diferente de 25:",(idade<>25))
escreval("Idade % 2 =0:",(idade%2=0))
escreval("Idade é diferente de 25 e o nome é igual a Marcos:",((idade<>25)E(nome=Marcos))


Fimalgoritmo